eureka:
  client:
    enabled: false

spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/jfund_test_currency_pairs}
    username: ${DB_USER:jfund}
    password: ${DB_PASSWORD:float123}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jfund_test_currency_pairs}
    username: ${DB_USER:jfund}
    password: ${DB_PASSWORD:float123}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
