spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/jfund_local_currency_pairs}
    username: ${DB_USER:jfund}
    password: ${DB_PASSWORD:float123}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jfund_local_currency_pairs}
    username: ${DB_USER:jfund}
    password: ${DB_PASSWORD:float123}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jfund_local_currency_pairs}
    user: ${DB_USER:jfund}
    password: ${DB_PASSWORD:float123}

currencyApi:
  accessKey: ${CURRENCY_ACCESS_KEY:ec142f3d17eb97486b71d155d609471a}

kafka:
  server: ${KAFKA_SERVER:localhost:9092}
  topic-name: "currency.keys"