spring:
  data:
    mongodb:
      host: ${DB_HOST_TEST:localhost}
      port: ${DB_PORT_TEST:27017}
      database: ${DB_NAME_TEST:jfundCurrencyPairsTest}
      username: ${DB_USER_TEST:dev}
      password: ${DB_PASSWORD_TEST:float123}
      authentication-database: admin

currencyApi:
  accessKey: ${CURRENCY_ACCESS_KEY:5619c1c4f1011d7b8c0b32054e2e676b}