eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: currency-pairs-service
  profiles:
    active: ${PROFILE:dev}

server:
  port: 8081


