spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:jfundCurrencyPairs}
      password: ${DB_PASSWORD:float123}
      username: ${DB_USER:develop}
      authentication-database: admin

currencyApi:
  accessKey: ${CURRENCY_ACCESS_KEY:5619c1c4f1011d7b8c0b32054e2e676b}