spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/jfund_local_currency_pairs}
    username: ${DB_USER:jfund}
    password: ${DB_PASSWORD:float123}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jfund_local_currency_pairs}
    username: ${DB_USER:jfund}
    password: ${DB_PASSWORD:float123}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  scheduler:
    enabled: ${SCHEDULER_ENABLED:true}
    load-currency-keys: ${LOAD_CURRENCY_KEYS_CRON:1 */5 * * * *}
    send-currency-keys: ${SEND_CURRENCY_KEYS_CRON:*/2 * * * * *}
  kafka:
    server: ${KAFKA_SERVER:localhost:9092}
    currency-keys-topic: ${CURRENCY_KEYS_TOPIC:currency-keys-topic}