eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: currency-pairs-service
  profiles:
    active: ${PROFILE:local}

server:
  port: 8081

app:
  kafka:
    server: ${KAFKA_SERVER:localhost:9092}
    currency-keys-topic: ${CURRENCY_KEYS_TOPIC:currency-keys-topic}
