
CREATE TABLE currency_pairs
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_key       VARCHAR(255)                            NOT NULL,
    to_key         VARCHAR(255)                            NOT NULL,
    key            VARCHAR(255)                            NOT NULL,
    show_in_candle BOOLEAN,
    CONSTRAINT pk_currency_pairs PRIMARY KEY (id)
);