CREATE TABLE currency_values
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key                   VARCHAR(255)                            NOT NULL,
    value                 FLOAT                                   NOT NULL,
    datetime_of_actuality TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    sent_to_candle_api    BOOLEAN                                 NOT NULL,
    created               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT "pk_currency_values" PRIMARY KEY (id)
);